
name: CI CD Pipeline

on:
  workflow_dispatch

jobs:
  compile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn compile
    
  security-check:

    runs-on: ubuntu-latest
    needs: compile

    steps:
    - uses: actions/checkout@v4
    - name: Trivy Installation
      run: |
        sudo apt-get install wget gnupg
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy

    - name: Trivy Fs Scan
      run: trivy fs --format table -o fs-report.json .
    - name: Gitleak Installation
      run: sudo apt install gitleaks -y
    - name: Gitleaks Code Scan Run
      run: gitleaks detect source . -r gitleaks-report.json -f json
  test:
    runs-on: ubuntu-latest
    needs: security-check
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Unit Test cases
      run: mvn test
  
  sonarqube:
    runs-on: self-hosted
    steps:
     - name: Checkout Code
       uses: actions/checkout@v4
     
     - name: Install Docker
       run: |
         choco install docker-cli -y
         choco install docker-desktop -y
     - name: Start Sonarqube Docker container
       run: |
          docker run -d --name sonarqube \
          -p 9000:9000 sonarqube:latest
          
     - name: Wait for SonarQube to be ready 
       run: | 
         echo "Waiting for SonarQube..." 
         timeout /t 60          
     - name: Verify SonarQube is running 
      run: | 
        curl http://localhost:9000
     - name: Show Docker info
       run: |
        docker ps -a
        docker logs --tail 200 sonarqube || true

     - name: Check port conflicts and resources
       run: |
          sudo lsof -i :9000 || true
          df -h
          free -m

          echo "Waiting for SonarQube..."
          until curl -s http://localhost:9000/api/system/status | grep -q '"status":"UP"'; do
          curl -s http://localhost:9000/api/system/status
          sleep 30
          done
          echo "SonarQube is ready"


     - name: Install Sonar Scanner
       run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
        unzip sonar-scanner-cli-*.zip
        sudo mv sonar-scanner-*/ /opt/sonar-scanner

     - name: Run SonarQube Scan
       env:
        SONAR_HOST_URL: "http://localhost:9000"
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       run: |
          /opt/sonar-scanner/bin/sonar-scanner \
          -Dsonar.projectKey=my-project \
          -Dsonar.sources=. \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN
          
